### ISSUE TITLE
hey i got a list 376ish of more from a raid that happened to me just now. hopefully here is fine

### ISSUE THREAD

**Issue by letterbit** [hackbolt/twitchbotsnbigots#1]
2e5weivb03
d3epipr7
g10c866jw5vqel
pihscvkgqiwm1
s6nfl75xgq
5c6donu8lm1wc
zuj4rwb1v
atzz1k
5mtyafyo40b4t
59ym659
tf5yx1n3w
ovrbvv27ccf
on0rt2qi3s
mlcfn8g
hcmr4
daq884q
5y1a28qcknmab1
p59ga094zwqaw
9bewwi9x
65tv2
nm50t1uaek
5ujixzgb0s2rcs
9qm3b8
pn0evgjgnb25y
a70hedrw9
nzpuit
a297xm1
sv34m9li
npy6ksef340944
zcbuc6t10ko6y7
xzo6uenfxk
tvrp7e2osz4hz
e0mmwvipb0cd
rb8tc0t3pa72
9tktj4568m4x2x
9p1rrbrlyb9x
i8zblhslzz4f9w
vscx5e
3asjlbbpdt50uw
tyyq4z3xy86l
7nt3mlfygx
qq3ruindpv
2rmuhqj33p4
s0hd5hw
ech0v0c
h2v5vtczelu
c14vz97ab13np
32u4mar1vbt
8u7hadf36
f64xqwd4wq
97jf7ii0
gbgsd04kp
4uoec
h1p04oky
q5artv7dej77k1
7nxti7l
o57hw7a
t77lq52
n0iwr
cjgycvauixnktv
0w43cd
t2bixl
beivg2a7ku
krxzwod9z5b1
ivqwxbos8
i01lupcw98gd
emb64r7yo2z9n
d5piiujdtzqjd7
mf4yx0wmyp
golyhacu8e
6q0ve0
891197nr5dgj
rr4stu263rvto
dlo3vd7ukgel
gnweev3uhspi
dywzewu
xw0p1
i6rvq9lr9l4cq5
4ydbynxy
ckc4wbtaxy7hov
tp7k80v
b8vgu
ugnu9jeq
yujq8kj
w36ff1
omwft
j1d3t
77fu2raq
fqcxwi3
gs4auw2l
vf3ont5rv9
i1qilhl0ugyb
j1i02532ghbc4u
zbpo7tmr2htf
f1k3holibl1
t6hmgfaearophf
yejg5rg3
5g2k0
ijul4
q0qttizdi2zzrq
o842bimzo
z1mu1c1
h1hncl6qsida63
3m7dd2
q1cev
xoszi62rz1
ayh7i7h612
zv3c37
27whhsniwihq
m631bd
ekgi5l
zw6jte5l3
u2q0ij7r71vp
urm6vn
er8iwa17pm
k4ywx88wroz4
s2yfz
y19y1
iaa5hjs
rz83s40w
26vr9hifdi61gm
4rd9bzqc21oe7
5dyar0tl48fv5
6my5gevwuynw
vilqtod66
2nn6j8tr
d9guklnshd
nb2c3sb
cjabtv4
t6fl0m6
zdsyqn
g56er8s3fo
j6dmnvqtbc34g1
v36w4fm
931px
2qzgu9arrn
b7lxev
dhwcduklun6l
4u0wx63u9biqz3
dew33lnm3bd9cb
wsk11kor9cftg
pywse6rymjo93z
v04fthzu4pw
0ke62jwtm681hi
379uhbb
0ti7i0ep
56eqgnpc2pf0f
jl6din
wojdgj6ys3h
ze243kgri0
ms3nj
benqpayz
ilefzzz
eohr4999rh739l
nj7uksfs48q5i
bh3s9i2pb9e8nw
ktc9qunl25
eop943r
8hfivpumidg016
yyplzt3t4g5p
dvgzqavmeoz6
l7xwdmt5b60
6gq8l
h7yfp
yo37mw6v0fz7
fataeb9
lbybgwpjiri
9b1h9c
nk0tdc24t
4q6eotgf
grh0nxi
h02622wp2
muilhfx22th
2whs5mv
w981bqcvlj
m92u8t
hbconikn
cl0gxwxzosycd
1stsnw
oue01zhxzsy
lgo1u41pe
ozqc8ro
rl3dv7pb1i2
p49rbbbnhpuxir
0zzfrmhid8ax9d
szc6mai
22jwnwrej
z6w4zu
p4gyyih2o4
s0oij4
rh3wfjd4sim9h
p6jsrmws6nk
ylrnh
xyqad420xa9e43
corzdx6vyk7
ucgy97f
e5mhpdeqtr7
za33u66a078
ny0w4bmu
h3tfrn6m1l3y
q47276ay39phr
fbconqrny9
r3eqss7x2ohey
ps3lo
g3he6fv6f829
bf311kj
1mukfo9kgef
kjspvvxrvy
a1w0y
1is2rbus5be
x5j2lz
od7uz4z72
a2jc6mylcx8
b8cof31ll
djnilze
4qo30m999
nnjuzyuxj9g
kvs3a
gli5o6rf69n
q4kig
v0uylrcyvuz
6l3ie4fwjr8q
iga51
r3whvx
t4kil22il0x8od
vh3phf
o6lk6ftaacb4yp
wsgxx35
rq5is2
t1ppjl
u8l4q
46xsmp5hbnf5j
i1hiyo9vzuljn
6da4c7
77x6dhjwle6g1h
aiov8fv6zucu6
s2578zky
wm2c99sz0
p3o81w1g
qk2byomem7
g7dipv
5aa06qyn6
h490ulwqldu2a
tkv4mxnys
otqju
p2p5nvvke5pu3
ynqb7
4prqa
9htue181sh1csr
qjiokp3al3
eggasm79jbs39
8kddg846
ndjc3tkfznrd
fe8u5vmchv4kpg
wi3n329r
2uzdyudvsgbv
1jt4r95j70j
dbq6fy0i6j4vt
4krrps8fr9ox9
rclktix8tdn
nu0di65si4
2waxaxhnohxide
6nccaypf2
5d24hz3dvn
hvs3k8q45b
2b5szk47hioh
6h0a86
ftarq3
8xpex2aegj5ju
6l9dkozff3ya
fdg7r2hba2ox
4yt5x5qxmo0
g93hez88
edipm78qw
046tsdb1ucnzxy
dr3vyi
en8ugt4
xt3w44kvop0ef
fswj0f11jxg
q1jlsed5
i4reuya4rkvkr
omcz0m8li
mdjehee9i1c
l2p8wt77
pm4i8
81dvfj
9htdgo9f40g
oeflh7zjum1sl9
ln7lmrlotf
imzd1pqvdk
kgl83zrrg
jcxmqt5nn5g
ykuipzwu
q5zj3
5k3gsv5c5kf59
wcoqlmobsn
yw6fb4m
847q8itzkar
b4g38ygyfwgdp
oprajlgg
tdv199jx
jkvhdx7vs9ht
z2j6xqm
03bi5ocz7ja
fzqn8
as16ib
zvgvj5
q3qunq8r4ser
6fdig2a23
vjyj9gga0o4e
szz70
no2jp4mg
kvryk86l
oqdkl9to
d3u1fs1k
sil6cyqagucje
7d2janie0g65o
shqp5uvj132
t2jqfzm
tlt0ckf49k
k46eyt7jy3
7wnnxv5b
zx6k3ius
wlww7
mzd9lc40
2wje656ly1
qi3vkgct
flt2j
vg07zprbz
c7mgm7q7ixfgv
owa9epmzp
2kzxy4rmhzm1
0uyx2jf
xptc1tsf
vryxdew
yohpfm
71hn7
kgzikas
b8z0yda
ct1kvz9f
6crksuggy7q
dg1j370wx9zqr7
t571r
7vp4ngrpadcc
cjzo6sio3g
c4bvyks
cp2tjam8dvozm
jbwifqbx2d3h
jto1fx
9ejmx7
umhfaqe1nm3
okzgw97ue
w4ffh4v
y107ne57
yhnqr5ub6sd
i0ekp1zw1b
ev0p6w714
n132jx1cdf
a14salkwa
m3wnzv8x694v
on2vvx3jmretm
mnr9ach5c8y4t
7rmszdp
cv7o4n8c
jmu8jb3r4gvit
ff53v24wjcqpli
h7k7a
pigsin06
cjbi4wqe13
ba9c3w1qf0iguu
89t07iqmx
yz6pums0i
82uv4h
yprxpxipt789ye
1cq50o
huo07o3tkvcw

**Comment by hackbolt** [comment]
Thank you, these are not on my list so I've added them.
