### ISSUE TITLE
FALSE POSITIVE

### ISSUE THREAD

**Issue by WaywardGravy** [hackbolt/twitchbotsnbigots#16]
My Twitch has been marked as a hack bot and i'm super upset about it. i am NOT a hack bot. twitch name WaywardGravy91. I do not understand where you guys come off marking me as a hack bot when i'm a freaking REAL PERSON WHO DOES NOTHING BUT SHOW LOVE AND SUPPORT. Take my name off. you've made me get banned in so many of my favorite streamers streams and this is ridiculous.

**Comment by pixelsuchter** [comment]
Removed you from the list. Sorry for any inconveniences, sometimes people get accidentally caught in crossfire when mods deal with raids and we have no good way of verifying the (sometimes very large) lists of names we get sent by people.

**Comment by WaywardGravy** [comment]
Thank you so much! This really upset me and im glad its resolved.

**Comment by hackbolt** [comment]
Hi there,

You will be removed. Please understand I compile this list in my own free
time outside of my full time job and it is subject to human error. Ive even
accidentally added myself TWICE now. I’ve been sent hundreds of lists of
accounts and it undoubtedly has false positives. It is why the false
positive list exists. It’s not a reflection of you, just an honest mistake
trying to help people.
