### ISSUE TITLE
New entry

### ISSUE THREAD

**Issue by thirdwheel** [hackbolt/twitchbotsnbigots#19]
This one followed me today... looks sus.

![image](https://user-images.githubusercontent.com/160601/132119398-af354aec-628d-4b88-b92e-3b3a288f81af.png)

**Comment by lhocke** [comment]
same account followed about 10 seconds after i went live friday, preemptively banned, matches pattern of some other listed accounts

**Comment by pixelsuchter** [comment]
Added them to the list
