### ISSUE TITLE
Text Based Documentation

### ISSUE THREAD

**Issue by MisutaaUrufu** [hackbolt/twitchbotsnbigots#7]
For those who are hearing impaired, unable to access the video, whom struggle with video instruction, or whom the video does not properly load (the names of the files are all blurry and compressed for me), is there a text based documentation that can be provided?

Having video only, even if it contains captions, limits the accessibility of the tool.

**Comment by pixelsuchter** [comment]
A text based documentation has been added, thanks for the suggestion
